Repository TCPShield/RealIP, pull requests merged in 2020-12, with the labels that each got.

#24 TCPShield v2.4
  README.md
  build.gradle
  src/main/java/net/tcpshield/tcpshield/Constants.java
  src/main/java/net/tcpshield/tcpshield/HandshakePacketHandler.java
  src/main/java/net/tcpshield/tcpshield/ReflectionUtils.java
  src/main/java/net/tcpshield/tcpshield/SignatureVerifier.java
  src/main/java/net/tcpshield/tcpshield/abstraction/TCPShieldConfig.java
  src/main/java/net/tcpshield/tcpshield/bukkit/TCPShieldBukkit.java
  src/main/java/net/tcpshield/tcpshield/bukkit/impl/BukkitConfigImpl.java
  src/main/java/net/tcpshield/tcpshield/bukkit/paper/PaperHandshakePacketHandler.java
  src/main/java/net/tcpshield/tcpshield/bukkit/paper/impl/PaperServerListPacketImpl.java
  src/main/java/net/tcpshield/tcpshield/bukkit/paper/impl/PaperServerListPingPlayerImpl.java
  src/main/java/net/tcpshield/tcpshield/bungee/impl/BungeeConfigImpl.java
  src/main/java/net/tcpshield/tcpshield/exception/InvalidIPException.java
  src/main/java/net/tcpshield/tcpshield/exception/InvalidTimestampException.java
  src/main/java/net/tcpshield/tcpshield/exception/SigningVerificationFailureException.java
  src/main/java/net/tcpshield/tcpshield/exception/TCPShieldIPListUpdaterException.java
  src/main/java/net/tcpshield/tcpshield/validation/IPListAutoUpdater.java
  src/main/java/net/tcpshield/tcpshield/validation/IPListUpdater.java
  src/main/java/net/tcpshield/tcpshield/validation/IPValidation.java
  src/main/java/net/tcpshield/tcpshield/validation/ITimestampValidator.java
  src/main/java/net/tcpshield/tcpshield/validation/TimestampValidation.java
  src/main/java/net/tcpshield/tcpshield/validation/cidr/CIDRChecker.java
  src/main/java/net/tcpshield/tcpshield/validation/cidr/CIDRMatcher.java
  src/main/java/net/tcpshield/tcpshield/validation/impl/DisabledTimestampValidatorImpl.java
  src/main/java/net/tcpshield/tcpshield/validation/impl/HTPDateTimestampValidatorImpl.java
  src/main/java/net/tcpshield/tcpshield/validation/impl/SystemTimeTimestampValidatorImpl.java
  src/main/java/net/tcpshield/tcpshield/velocity/impl/VelocityConfigImpl.java
  src/main/resources/bungee.yml
  src/main/resources/plugin.yml
  src/main/resources/signing_pub.key
  src/main/resources/velocity-plugin.json
  src/test/java/net/tcpshield/tcpshield/HandshakePacketHandlerTest.java
  src/test/java/net/tcpshield/tcpshield/SignatureObjectVerifierTest.java
  src/test/java/net/tcpshield/tcpshield/TestConstants.java
  src/test/java/net/tcpshield/tcpshield/impl/TestConfigImpl.java
  src/test/java/net/tcpshield/tcpshield/impl/TestPlayerImpl.java
Labels: bug, enhancement

#27 Adds a check if the webserver returns 200 on pulling the IP list
  src/main/java/net/tcpshield/tcpshield/exception/TCPShieldIPListUpdaterException.java
  src/main/java/net/tcpshield/tcpshield/validation/IPListUpdater.java
Labels: bug

#28 Update .gitignore
  .gitignore
Labels: documentation
